export const SELECTORS = {
  banners: {
    success: '.success-banner',
    error: '[role="alert"]',
  },
  form: {
    fieldError: '.field-error',
    ingredients: '.ingredient-fields',
    steps: '.step-fields',
  },
  recipe: {
    card: '.recipe-card',
    title: '.recipe-title',
    deleteBtn: '.btn-danger',
    confirmDelete: '.btn-danger-filled',
  },
  chat: {
    fab: '[data-testid="chat-fab"]',
    panel: '[data-testid="chat-panel"]',
    backdrop: '[data-testid="chat-backdrop"]',
    close: '[data-testid="chat-close"]',
    clear: '[data-testid="chat-clear"]',
    send: '[data-testid="chat-send"]',
    input: '[data-testid="chat-input"]',
    welcome: '[data-testid="chat-welcome"]',
    // Multi-element / state-based — kept as class selectors (each li is a
    // separate item, role-based bubbles distinguish user vs assistant).
    examples: '.chat-examples li',
    userMessage: '.chat-message.role-user .chat-bubble',
    assistantMessage: '.chat-message.role-assistant .chat-bubble',
  },
  mealPlanner: {
    dayCard: '.day-card',
    dayHeader: '.day-header',
    mealTitle: '.meal-title',
    mealServings: '.meal-servings',
    mealFreetext: '.meal-freetext',
    mealState: '.meal-state',
    emptySlot: '.empty-slot',
    clearBtn: '.clear-btn',
    navPrev: '.planner-header .nav-btn:first-child',
    navNext: '.planner-header .nav-btn:last-child',
    weekLabel: '.planner-header h1',
    generateBtn: '.generate-btn',
    shoppingResult: '.shopping-result',
    plannerActions: '.planner-actions',
    loading: '.loading',
    error: '.error',
    retryBtn: '.retry-btn',
  },
  shopping: {
    categoryGroup: '.category-group',
    itemName: '.item-name',
    addInput: '.add-input',
    emptyState: '.empty-state',
    progressBar: '.progress-bar',
    retryBtn: '.retry-btn',
  },
  profileSettings: {
    title: '.profile-settings h1',
    servingsInput: '#servings',
    dietaryTypeSelect: '#dietaryType',
    cookingEffortSelect: '#cookingEffort',
    checkboxLabel: '.checkbox-label',
    saveBtn: '.save-btn',
    savedIndicator: '.saved-indicator',
    settingsSection: '.settings-section',
    loading: '.loading',
    error: '.error',
    retryBtn: '.retry-btn',
  },
  header: {
    userMenuToggle: '[data-testid="user-menu-toggle"]',
    langSwitch: '[data-testid="lang-switch"]',
    logout: '[data-testid="logout"]',
  },
  keycloak: {
    username: '#username',
    password: '#password',
    loginBtn: '#kc-login',
  },
} as const;
