export const SELECTORS = {
  banners: {
    success: '.success-banner',
    error: '[role="alert"]',
  },
  form: {
    fieldError: '.field-error',
    ingredients: '.ingredient-fields',
    steps: '.step-fields',
  },
  recipe: {
    card: '[data-testid="recipe-card"]',
    title: '.recipe-title',
    deleteBtn: '[data-testid="recipe-delete-btn"]',
    // confirmDelete is the modal confirmation button inside yn-confirm-dialog;
    // shared component, scope-agnostic — keep CSS selector for now until the
    // dialog gets its own data-testid in a follow-up.
    confirmDelete: '.btn-danger-filled',
  },
  chat: {
    fab: '.command-fab',
    panel: '.chat-panel',
    backdrop: '.chat-backdrop',
    close: '.chat-close',
    clear: '.chat-clear',
    send: '.chat-send',
    input: '.chat-input textarea',
    welcome: '.chat-welcome',
    examples: '.chat-examples li',
    userMessage: '.chat-message.role-user .chat-bubble',
    assistantMessage: '.chat-message.role-assistant .chat-bubble',
  },
  mealPlanner: {
    dayCard: '.day-card',
    dayHeader: '.day-header',
    mealTitle: '.meal-title',
    mealServings: '.meal-servings',
    mealFreetext: '.meal-freetext',
    mealState: '.meal-state',
    emptySlot: '.empty-slot',
    clearBtn: '.clear-btn',
    navPrev: '[data-testid="meal-planner-nav-prev"]',
    navNext: '[data-testid="meal-planner-nav-next"]',
    weekLabel: '.planner-header h1',
    generateBtn: '.generate-btn',
    shoppingResult: '.shopping-result',
    plannerActions: '.planner-actions',
    loading: '.loading',
    error: '.error',
    retryBtn: '.retry-btn',
  },
  shopping: {
    categoryGroup: '.category-group',
    itemName: '.item-name',
    addInput: '.add-input',
    emptyState: '.empty-state',
    progressBar: '.progress-bar',
    retryBtn: '.retry-btn',
  },
  profileSettings: {
    title: '.profile-settings h1',
    servingsInput: '#servings',
    dietaryTypeSelect: '#dietaryType',
    cookingEffortSelect: '#cookingEffort',
    checkboxLabel: '.checkbox-label',
    saveBtn: '.save-btn',
    savedIndicator: '.saved-indicator',
    settingsSection: '.settings-section',
    loading: '.loading',
    error: '.error',
    retryBtn: '.retry-btn',
  },
  header: {
    userMenuToggle: '[data-testid="user-menu-toggle"]',
    langSwitch: '[data-testid="lang-switch"]',
    logout: '[data-testid="logout"]',
  },
  keycloak: {
    username: '#username',
    password: '#password',
    loginBtn: '#kc-login',
  },
} as const;
