// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartSolutionsLab.Yumney.Shopping.Infrastructure.Persistence;

#nullable disable

namespace SmartSolutionsLab.Yumney.Shopping.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ShoppingDbContext))]
    [Migration("20260410145134_AddShoppingLedger")]
    partial class AddShoppingLedger
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartSolutionsLab.Yumney.Shopping.Domain.ShoppingLedger.ShoppingLedger", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("Owner")
                        .IsUnique();

                    b.ToTable("ShoppingLedgers", (string)null);
                });

            modelBuilder.Entity("SmartSolutionsLab.Yumney.Shopping.Domain.ShoppingList.ShoppingList", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("RecipeReference")
                        .HasColumnType("uuid")
                        .HasColumnName("RecipeIdentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Owner");

                    b.HasIndex("Owner", "CreatedAt");

                    b.HasIndex("Owner", "Title");

                    b.ToTable("ShoppingLists", (string)null);
                });

            modelBuilder.Entity("SmartSolutionsLab.Yumney.Shopping.Domain.ShoppingLedger.ShoppingLedger", b =>
                {
                    b.OwnsMany("SmartSolutionsLab.Yumney.Shopping.Domain.ShoppingLedger.LedgerTransaction", "Transactions", b1 =>
                        {
                            b1.Property<Guid>("ShoppingLedgerId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("Action")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<string>("ItemName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<DateTime>("OccurredAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<decimal>("Quantity")
                                .HasColumnType("numeric");

                            b1.Property<string>("Source")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<string>("Unit")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.HasKey("ShoppingLedgerId", "Id");

                            b1.HasIndex("OccurredAt");

                            b1.ToTable("LedgerTransactions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ShoppingLedgerId");
                        });

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("SmartSolutionsLab.Yumney.Shopping.Domain.ShoppingList.ShoppingList", b =>
                {
                    b.OwnsMany("SmartSolutionsLab.Yumney.Shopping.Domain.ShoppingList.ShoppingListItem", "Items", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<bool>("IsChecked")
                                .HasColumnType("boolean");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<Guid>("ShoppingListId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("ShoppingListId");

                            b1.ToTable("ShoppingListItems", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ShoppingListId");

                            b1.OwnsOne("SmartSolutionsLab.Yumney.Shopping.Domain.ShoppingList.Quantity", "Quantity", b2 =>
                                {
                                    b2.Property<Guid>("ShoppingListItemId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("numeric")
                                        .HasColumnName("Amount");

                                    b2.Property<string>("Unit")
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("Unit");

                                    b2.HasKey("ShoppingListItemId");

                                    b2.ToTable("ShoppingListItems");

                                    b2.WithOwner()
                                        .HasForeignKey("ShoppingListItemId");
                                });

                            b1.Navigation("Quantity");
                        });

                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
