// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartSolutionsLab.Yumney.Users.Infrastructure.Persistence;

#nullable disable

namespace SmartSolutionsLab.Yumney.Users.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(UsersDbContext))]
    [Migration("20260409200433_AddDietaryProfile")]
    partial class AddDietaryProfile
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartSolutionsLab.Yumney.Users.Domain.AppUserProfile.AppUserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("KeycloakUserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("PreferredUnitSystem")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("KeycloakUserId")
                        .IsUnique();

                    b.ToTable("AppUserProfiles", (string)null);
                });

            modelBuilder.Entity("SmartSolutionsLab.Yumney.Users.Domain.UserActivity.UserActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("RecipeIdentifier")
                        .HasColumnType("uuid");

                    b.Property<string>("RecipeTitle")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Owner", "OccurredAt")
                        .IsDescending(false, true);

                    b.ToTable("UserActivities", (string)null);
                });

            modelBuilder.Entity("SmartSolutionsLab.Yumney.Users.Domain.AppUserProfile.AppUserProfile", b =>
                {
                    b.OwnsOne("SmartSolutionsLab.Yumney.Users.Domain.AppUserProfile.DietaryProfile", "DietaryProfile", b1 =>
                        {
                            b1.Property<Guid>("AppUserProfileId")
                                .HasColumnType("uuid");

                            b1.Property<string>("CookingEffort")
                                .HasMaxLength(25)
                                .HasColumnType("character varying(25)")
                                .HasColumnName("CookingEffort");

                            b1.Property<string>("DietaryType")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("DietaryType");

                            b1.Property<string>("Restrictions")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("DietaryRestrictions");

                            b1.HasKey("AppUserProfileId");

                            b1.ToTable("AppUserProfiles");

                            b1.WithOwner()
                                .HasForeignKey("AppUserProfileId");

                            b1.OwnsOne("SmartSolutionsLab.Yumney.Users.Domain.AppUserProfile.WeeklyBalanceGoals", "BalanceGoals", b2 =>
                                {
                                    b2.Property<Guid>("DietaryProfileAppUserProfileId")
                                        .HasColumnType("uuid");

                                    b2.Property<int?>("MaxRedMeatMeals")
                                        .HasColumnType("integer")
                                        .HasColumnName("MaxRedMeatMeals");

                                    b2.Property<int?>("MinVeggieMeals")
                                        .HasColumnType("integer")
                                        .HasColumnName("MinVeggieMeals");

                                    b2.HasKey("DietaryProfileAppUserProfileId");

                                    b2.ToTable("AppUserProfiles");

                                    b2.WithOwner()
                                        .HasForeignKey("DietaryProfileAppUserProfileId");
                                });

                            b1.Navigation("BalanceGoals")
                                .IsRequired();
                        });

                    b.Navigation("DietaryProfile")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
