// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartSolutionsLab.Yumney.Users.Infrastructure.Persistence;

#nullable disable

namespace SmartSolutionsLab.Yumney.Users.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(UsersDbContext))]
    [Migration("20260504151020_AddProfilePreferences")]
    partial class AddProfilePreferences
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartSolutionsLab.Yumney.Users.Domain.AppUserProfile.AppUserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("DefaultServings")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(4);

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("KeycloakUserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("PreferredUnitSystem")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("system");

                    b.HasKey("Id");

                    b.HasIndex("KeycloakUserId")
                        .IsUnique();

                    b.ToTable("AppUserProfiles", (string)null);
                });

            modelBuilder.Entity("SmartSolutionsLab.Yumney.Users.Domain.StaplesList.StaplesList", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("Owner")
                        .IsUnique();

                    b.ToTable("StaplesLists", (string)null);
                });

            modelBuilder.Entity("SmartSolutionsLab.Yumney.Users.Domain.UserActivity.UserActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("RecipeIdentifier")
                        .HasColumnType("uuid");

                    b.Property<string>("RecipeTitle")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Owner", "OccurredAt")
                        .IsDescending(false, true);

                    b.ToTable("UserActivities", (string)null);
                });

            modelBuilder.Entity("SmartSolutionsLab.Yumney.Users.Domain.AppUserProfile.AppUserProfile", b =>
                {
                    b.OwnsOne("SmartSolutionsLab.Yumney.Users.Domain.AppUserProfile.DietaryProfile", "DietaryProfile", b1 =>
                        {
                            b1.Property<Guid>("AppUserProfileId")
                                .HasColumnType("uuid");

                            b1.Property<string>("CookingEffort")
                                .HasMaxLength(25)
                                .HasColumnType("character varying(25)")
                                .HasColumnName("CookingEffort");

                            b1.Property<string>("DietaryType")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("DietaryType");

                            b1.Property<string>("Restrictions")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("DietaryRestrictions");

                            b1.HasKey("AppUserProfileId");

                            b1.ToTable("AppUserProfiles");

                            b1.WithOwner()
                                .HasForeignKey("AppUserProfileId");

                            b1.OwnsOne("SmartSolutionsLab.Yumney.Users.Domain.AppUserProfile.WeeklyBalanceGoals", "BalanceGoals", b2 =>
                                {
                                    b2.Property<Guid>("DietaryProfileAppUserProfileId")
                                        .HasColumnType("uuid");

                                    b2.Property<int?>("MaxRedMeatMeals")
                                        .HasColumnType("integer")
                                        .HasColumnName("MaxRedMeatMeals");

                                    b2.Property<int?>("MinVeggieMeals")
                                        .HasColumnType("integer")
                                        .HasColumnName("MinVeggieMeals");

                                    b2.HasKey("DietaryProfileAppUserProfileId");

                                    b2.ToTable("AppUserProfiles");

                                    b2.WithOwner()
                                        .HasForeignKey("DietaryProfileAppUserProfileId");
                                });

                            b1.Navigation("BalanceGoals")
                                .IsRequired();
                        });

                    b.OwnsOne("SmartSolutionsLab.Yumney.Users.Domain.AppUserProfile.NotificationPreferences", "NotificationPreferences", b1 =>
                        {
                            b1.Property<Guid>("AppUserProfileId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("TimerHapticFeedback")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(true)
                                .HasColumnName("TimerHapticFeedback");

                            b1.Property<bool>("TimerSoundAlerts")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(true)
                                .HasColumnName("TimerSoundAlerts");

                            b1.HasKey("AppUserProfileId");

                            b1.ToTable("AppUserProfiles");

                            b1.WithOwner()
                                .HasForeignKey("AppUserProfileId");
                        });

                    b.OwnsOne("SmartSolutionsLab.Yumney.Users.Domain.AppUserProfile.VoiceSettings", "VoiceSettings", b1 =>
                        {
                            b1.Property<Guid>("AppUserProfileId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("AutoReadInCookMode")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("VoiceAutoReadInCookMode");

                            b1.Property<bool>("Enabled")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(true)
                                .HasColumnName("VoiceEnabled");

                            b1.Property<string>("Speed")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasDefaultValue("normal")
                                .HasColumnName("VoiceSpeed");

                            b1.HasKey("AppUserProfileId");

                            b1.ToTable("AppUserProfiles");

                            b1.WithOwner()
                                .HasForeignKey("AppUserProfileId");
                        });

                    b.Navigation("DietaryProfile")
                        .IsRequired();

                    b.Navigation("NotificationPreferences")
                        .IsRequired();

                    b.Navigation("VoiceSettings")
                        .IsRequired();
                });

            modelBuilder.Entity("SmartSolutionsLab.Yumney.Users.Domain.StaplesList.StaplesList", b =>
                {
                    b.OwnsMany("SmartSolutionsLab.Yumney.Users.Domain.StaplesList.StapleItem", "Items", b1 =>
                        {
                            b1.Property<Guid>("StaplesListId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Name");

                            b1.HasKey("StaplesListId", "Id");

                            b1.ToTable("StapleItems", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("StaplesListId");
                        });

                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
