// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartSolutionsLab.Yumney.Recipes.Infrastructure.Persistence;

#nullable disable

namespace SmartSolutionsLab.Yumney.Recipes.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RecipesDbContext))]
    [Migration("20260408221825_AddRecipeFavorites")]
    partial class AddRecipeFavorites
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartSolutionsLab.Yumney.Recipes.Domain.Recipe.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int?>("CookingTime")
                        .HasColumnType("integer")
                        .HasColumnName("CookingTimeMinutes");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Difficulty")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Language")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("PreparationTime")
                        .HasColumnType("integer")
                        .HasColumnName("PreparationTimeMinutes");

                    b.Property<int?>("Servings")
                        .HasColumnType("integer");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Owner");

                    b.HasIndex("Owner", "CreatedAt");

                    b.HasIndex("Owner", "Title");

                    b.HasIndex("SourceUrl", "Owner")
                        .IsUnique()
                        .HasFilter("\"SourceUrl\" IS NOT NULL");

                    b.ToTable("Recipes", (string)null);
                });

            modelBuilder.Entity("SmartSolutionsLab.Yumney.Recipes.Domain.RecipeFavorite.RecipeFavorite", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FavoritedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("RecipeIdentifier")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Owner", "RecipeIdentifier")
                        .IsUnique();

                    b.ToTable("RecipeFavorites", (string)null);
                });

            modelBuilder.Entity("SmartSolutionsLab.Yumney.Recipes.Domain.Recipe.Recipe", b =>
                {
                    b.OwnsMany("SmartSolutionsLab.Yumney.Recipes.Domain.Recipe.Ingredient", "Ingredients", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<Guid>("RecipeId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("RecipeId");

                            b1.ToTable("RecipeIngredients", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RecipeId");

                            b1.OwnsOne("SmartSolutionsLab.Yumney.Recipes.Domain.Recipe.Quantity", "Quantity", b2 =>
                                {
                                    b2.Property<Guid>("IngredientId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("numeric")
                                        .HasColumnName("Amount");

                                    b2.Property<string>("Unit")
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("Unit");

                                    b2.HasKey("IngredientId");

                                    b2.ToTable("RecipeIngredients");

                                    b2.WithOwner()
                                        .HasForeignKey("IngredientId");
                                });

                            b1.Navigation("Quantity");
                        });

                    b.OwnsMany("SmartSolutionsLab.Yumney.Recipes.Domain.Recipe.RecipeTag", "Tags", b1 =>
                        {
                            b1.Property<Guid>("RecipeId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("Tag");

                            b1.HasKey("RecipeId", "Id");

                            b1.ToTable("RecipeTags", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RecipeId");
                        });

                    b.OwnsMany("SmartSolutionsLab.Yumney.Recipes.Domain.Recipe.Step", "Steps", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)");

                            b1.Property<int>("Number")
                                .HasColumnType("integer");

                            b1.Property<Guid>("RecipeId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("RecipeId");

                            b1.ToTable("RecipeSteps", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RecipeId");
                        });

                    b.Navigation("Ingredients");

                    b.Navigation("Steps");

                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
