/**
 * ---------------------------------------------------------------
 * AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
 *
 * Generated by: scripts/generate-validation-constants.mjs
 * Source: src/Yumney.*.Domain/ value objects
 * Run: yarn generate:validation
 * ---------------------------------------------------------------
 */

export const VALIDATION = {
  RECIPES: {
    DIFFICULTY: { MAX_LENGTH: 50 },
    IMAGE_URL: { MAX_LENGTH: 2048 },
    INGREDIENT_NAME: { MAX_LENGTH: 200 },
    OWNER_IDENTIFIER: { MAX_LENGTH: 255 },
    RECIPE_DESCRIPTION: { MAX_LENGTH: 2000 },
    RECIPE_LANGUAGE: { MAX_LENGTH: 10 },
    RECIPE_TAG: { MAX_LENGTH: 50 },
    RECIPE_TITLE: { MAX_LENGTH: 200 },
    RECIPE_URL: { MAX_LENGTH: 2048 },
    SEARCH_TERM: { MAX_LENGTH: 200 },
    SERVINGS: { MIN_VALUE: 1 },
    STEP_DESCRIPTION: { MAX_LENGTH: 2000 },
    UNIT: { MAX_LENGTH: 50 },
  },
  SHOPPING: {
    ITEM_NAME: { MAX_LENGTH: 200 },
    OWNER_IDENTIFIER: { MAX_LENGTH: 255 },
    SHOPPING_LIST_TITLE: { MAX_LENGTH: 200 },
    UNIT: { MAX_LENGTH: 50 },
  },
  USERS: {
    DISPLAY_NAME: { MAX_LENGTH: 200 },
    EMAIL: { MAX_LENGTH: 254 },
    KEYCLOAK_USER_ID: { MAX_LENGTH: 255 },
    PASSWORD: { DIGIT_PATTERN: '[0-9]', LOWERCASE_PATTERN: '[a-z]', MIN_LENGTH: 8, UPPERCASE_PATTERN: '[A-Z]' },
    PREFERRED_LANGUAGE: { MAX_LENGTH: 10 },
    PREFERRED_UNIT_SYSTEM: { MAX_LENGTH: 20 },
  },
} as const;
