// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartSolutionsLab.Yumney.MealPlan.Infrastructure.Persistence;

#nullable disable

namespace SmartSolutionsLab.Yumney.MealPlan.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MealPlanDbContext))]
    [Migration("20260411191750_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartSolutionsLab.Yumney.MealPlan.Domain.WeeklyPlan.WeeklyPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Week")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("Owner", "Week")
                        .IsUnique();

                    b.ToTable("WeeklyPlans", (string)null);
                });

            modelBuilder.Entity("SmartSolutionsLab.Yumney.MealPlan.Domain.WeeklyPlan.WeeklyPlan", b =>
                {
                    b.OwnsMany("SmartSolutionsLab.Yumney.MealPlan.Domain.WeeklyPlan.MealSlot", "Slots", b1 =>
                        {
                            b1.Property<Guid>("WeeklyPlanId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("Day")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)");

                            b1.Property<Guid?>("RecipeIdentifier")
                                .HasColumnType("uuid");

                            b1.Property<string>("RecipeTitle")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<int>("Servings")
                                .HasColumnType("integer");

                            b1.HasKey("WeeklyPlanId", "Id");

                            b1.ToTable("MealSlots", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("WeeklyPlanId");
                        });

                    b.Navigation("Slots");
                });
#pragma warning restore 612, 618
        }
    }
}
