// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartSolutionsLab.Yumney.MealPlan.Infrastructure.Persistence;

#nullable disable

namespace SmartSolutionsLab.Yumney.MealPlan.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MealPlanDbContext))]
    [Migration("20260418115718_IntroduceSlotRecipeReference")]
    partial class IntroduceSlotRecipeReference
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartSolutionsLab.Yumney.MealPlan.Domain.WeeklyPlan.WeeklyPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsExtendedMode")
                        .HasColumnType("boolean");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Week")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("Owner", "Week")
                        .IsUnique();

                    b.ToTable("WeeklyPlans", (string)null);
                });

            modelBuilder.Entity("SmartSolutionsLab.Yumney.MealPlan.Domain.WeeklyPlan.WeeklyPlan", b =>
                {
                    b.OwnsMany("SmartSolutionsLab.Yumney.MealPlan.Domain.WeeklyPlan.MealSlot", "Slots", b1 =>
                        {
                            b1.Property<Guid>("WeeklyPlanId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)");

                            b1.Property<string>("Day")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)");

                            b1.Property<string>("FreetextLabel")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("LeftoverLabel")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("LeftoverSourceDay")
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)");

                            b1.Property<string>("LeftoverSourceMealType")
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)");

                            b1.Property<string>("MealType")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)");

                            b1.Property<int>("Servings")
                                .HasColumnType("integer");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)");

                            b1.HasKey("WeeklyPlanId", "Id");

                            b1.ToTable("MealSlots", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("WeeklyPlanId");

                            b1.OwnsOne("SmartSolutionsLab.Yumney.MealPlan.Domain.WeeklyPlan.SlotRecipeReference", "Recipe", b2 =>
                                {
                                    b2.Property<Guid>("MealSlotWeeklyPlanId")
                                        .HasColumnType("uuid");

                                    b2.Property<Guid>("MealSlotId")
                                        .HasColumnType("uuid");

                                    b2.Property<Guid>("RecipeIdentifier")
                                        .HasColumnType("uuid")
                                        .HasColumnName("RecipeIdentifier");

                                    b2.Property<string>("Title")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("character varying(200)")
                                        .HasColumnName("RecipeTitle");

                                    b2.HasKey("MealSlotWeeklyPlanId", "MealSlotId");

                                    b2.ToTable("MealSlots");

                                    b2.WithOwner()
                                        .HasForeignKey("MealSlotWeeklyPlanId", "MealSlotId");
                                });

                            b1.Navigation("Recipe");
                        });

                    b.Navigation("Slots");
                });
#pragma warning restore 612, 618
        }
    }
}
